### ISSUE TITLE
The wrong bundle id

### ISSUE THREAD

**Issue by axelburks** [JMccormick264/YouTubePP#15]
The new version "YouTube.v12.47.16_v1.4r-91.With.Display.Name.ipa" can not overwrite the old version.
I found that the bundle id of it was changed to  "com.Justin.YouTube--" and the old version is "com.Justin.YouTube". 
And the bundle id of "YouTube.v12.47.16_v1.4r-91.Tweaked.Install.alongside.the.app.store.app.ipa" is  "com.Justin.Twitter--". So wired.

**Comment by RobinTR** [comment]
I cant install latest youtube++ youre right

**Comment by JMccormick264** [comment]
I am fixing it. Will change how I do the Bundle IDs.

**Comment by JMccormick264** [comment]
Should be fixed in the 12.49 version I just re-uploaded. [here](https://github.com/JMccormick264/YouTubePP/releases/tag/App_v12.49) Will have to install the IPAs again, but I think I figured a better way of doing the Bundle ID for the different versions. Install alongside, ++ Display, etc.
