### ISSUE TITLE
App Won’t Open Anymore

### ISSUE THREAD

**Issue by stephenshutters** [JMccormick264/YouTubePP#23]
As of last night, 08/20/18, YT++ no longer opens without an immediate crash. No amount of phone resets has helped.

**Comment by shusain93** [comment]
What are you walking about? It works fine for me

**Comment by stephenshutters** [comment]
The strange thing is that it doesn't show up in my logs. You can see in [this screen capture](https://youtu.be/svt8eKMsgng).

**Comment by shusain93** [comment]
Did your certificate expire? Fairly certain even with developer certs you have to resign after a renew. Try connecting to your Mac and watching console.app

**Comment by stephenshutters** [comment]
Oh, wow. I feel quite foolish. You are correct that my certificate expired. I apologize for the false alarm.
