### ISSUE TITLE
Download link error

### ISSUE THREAD

**Issue by archipilot** [JMccormick264/YouTubePP#6]
can you relink the download page

**Comment by royerlraph79** [comment]
Same issue here

**Comment by welaxxx** [comment]
yes youtube link not working

**Comment by ElmHoe** [comment]
Releases of the iPA file are committed to /releases/
https://github.com/JMccormick264/YouTubePP/releases

**Comment by JMccormick264** [comment]
I have fixed the Readme to include the release link.
https://github.com/JMccormick264/YouTubePP/releases <-- is where the releases are
