### ISSUE TITLE
How the hell can we download the app??

### ISSUE THREAD

**Issue by royerlraph79** [JMccormick264/YouTubePP#8]
When we click on YouTube Repo it redirects us to the exact same page!! It’s been lasting for weeks and nobody has done anything, it’s frustrating!

**Comment by ElmHoe** [comment]
Releases of the iPA file are committed to /releases/
https://github.com/JMccormick264/YouTubePP/releases

**Comment by royerlraph79** [comment]
Ah, thank you so much. However, when we click on YouTube Repo at https://github.com/JMccormick264/YouTubePP/ the link redirects to https://github.com/JMccormick264/YouTubePP/ and not https://github.com/JMccormick264/YouTubePP/releases

**Comment by JMccormick264** [comment]
ahh. I will fix that. Thank you

**Comment by JMccormick264** [comment]
Been fixed.
